### ISSUE TITLE
Unable to upload metadata

### ISSUE THREAD

**Issue by c0m3tx** [nkokkos/vws#6]
Hi,
I'm trying to upload metadata with a target.

The target gets uploaded and parsed by Vuforia, but no metadata is attached. Any idea?

Here is a snipped from my code which doesn't work properly
    
    # getting a connection to Vuforia
    connection = Vws::Api.new(VUFORIA_KEY, VUFORIA_SECRET)
    # getting text from metadata file into metadata_content
    metadata_content = File.open(Rails.root.join('public',uploaded_io.original_filename)).read
    # building the new target on Vuforia
    result = JSON.parse(connection.add_target(@target.name, Rails.root.join('public','targets', @target.image_file_name), 100.0, true, metadata_content))

**Comment by nkokkos** [comment]
Hi
Try this fork https://github.com/goodwinproject/vws until I get a better look at this. 
Thanx

**Comment by c0m3tx** [comment]
Hi nkokkos,
thanks for the info, it works fine now.

**Comment by c0m3tx** [comment]
Sent you a PR which fixes the metadata issue.

**Comment by nkokkos** [comment]
Merged Fixed metadata uploading and updating. 
Thank you @c0m3tx !
