### ISSUE TITLE
All methods return nil

### ISSUE THREAD

**Issue by macsrok** [nkokkos/vws#8]
Hello,

I'm trying to implement your gem but all methods seem to return nil. Am I just missing a step or does the gem need an update after the purchase of Vuforia by PTC

`c = Vws::Api.new("#####FOO#####", "#####BAR#####")`

 `=> # <Vws::Api:0x0000010aaa1558 @accesskey="#####FOO#####", @secretkey="#####BAR#####"> `

 `c.summary`
 `=> nil `

`c.list_targets`
 `=> nil `

`c.add_target("new_brick", "/path/to/brick.jpg", 20, true, nil)`
 `=> nil `

**Comment by nkokkos** [comment]
I am sorry. I haven't looked at this gem for a while after Vuforia was purchased by PTC. I will try my best to go over it, look at the api endpoints (maybe they have changed since PTC acquisition) and run some tests

**Comment by nkokkos** [comment]
I just checked it. It works. Which access and secret keys do you use? You are supposed to use the cloud "Server Access Keys" as parameters to Vws::Api.new. 

Here is a screenshot from my console of the Vuforia Target Manager Web Interface:

![vuforia](https://cloud.githubusercontent.com/assets/38037/11972209/c05be954-a951-11e5-881b-e8525f975168.jpg)

Try to use the web console to upload some targets and then use the vws library to see if it returns a summary of the targets.

**Comment by macsrok** [comment]
I updated my ruby and that seemed to fix it.

**Comment by nkokkos** [comment]
Ok. I am glad you sorted it out. I am going to close this issue.
